//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCash
    {
        public int IdCash { get; set; }
        public string Discription { get; set; }
        public System.DateTime Date { get; set; }
        public double Sum { get; set; }
        public int Operation_id { get; set; }
        public string Dogovor { get; set; }
        public int OrderOrSale_Id { get; set; }
    
        public virtual DbOperations Operation { get; set; }
        public virtual DbOrdersOrSales OrderOrSale { get; set; }
    }
}
