//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbGoods
    {
        public DbGoods()
        {
            this.OrderStorageSaleGoods = new HashSet<DbOrderStorageSaleGoods>();
        }
    
        public int IdGoods { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DbOrderStorageSaleGoods> OrderStorageSaleGoods { get; set; }
    }
}
