//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOrderStorageSaleGoods
    {
        public int IdGoods { get; set; }
        public int Goods_id { get; set; }
        public int Count { get; set; }
        public int Module_id { get; set; }
        public double PriceOfUnit { get; set; }
        public string Comment { get; set; }
        public int OrderOrStorageOrSale { get; set; }
        public int OrderOrSale_Id { get; set; }
        public bool isDelete { get; set; }
    
        public virtual DbGoods Goods { get; set; }
        public virtual DbModules Module { get; set; }
        public virtual DbOrdersOrSales OrderOrSale { get; set; }
    }
}
