//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPartners
    {
        public DbPartners()
        {
            this.OrderOrSales = new HashSet<DbOrdersOrSales>();
        }
    
        public int IdPartner { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public System.DateTime Data { get; set; }
        public string Phone { get; set; }
        public int Relationship_id { get; set; }
        public string Inn { get; set; }
        public string Bik { get; set; }
        public string Director { get; set; }
    
        public virtual ICollection<DbOrdersOrSales> OrderOrSales { get; set; }
        public virtual DbRelationships Relationship { get; set; }
    }
}
