//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPersonnels
    {
        public DbPersonnels()
        {
            this.OrderOrSale = new HashSet<DbOrdersOrSales>();
            this.Tasks = new HashSet<DbTask>();
        }
    
        public int IdPersonnel { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SoName { get; set; }
        public System.DateTime Dtr { get; set; }
        public bool Gender { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public int Post_id { get; set; }
        public string Password { get; set; }

        public string LittleName
        {
            get { return String.Format("{0} {1}.{2}.", LastName, FirstName[0], SoName[0]); }
        }

        public string FullName
        {
            get { return String.Format("{0} {1} {2}", LastName, FirstName, SoName); }
        }
    
        public virtual ICollection<DbOrdersOrSales> OrderOrSale { get; set; }
        public virtual DbPosts Post { get; set; }
        public virtual ICollection<DbTask> Tasks { get; set; }
    }
}
