//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPosts
    {
        public DbPosts()
        {
            this.Personnels = new HashSet<DbPersonnels>();
        }
    
        public int id_post { get; set; }
        public string Post { get; set; }
        public string Discription { get; set; }
    
        public virtual ICollection<DbPersonnels> Personnels { get; set; }
    }
}
