//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbRelationships
    {
        public DbRelationships()
        {
            this.Partners = new HashSet<DbPartners>();
        }
    
        public int IdRelationship { get; set; }
        public string Relationship { get; set; }
    
        public virtual ICollection<DbPartners> Partners { get; set; }
    }
}
