//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbStatus
    {
        public DbStatus()
        {
            this.OrderOrSales = new HashSet<DbOrdersOrSales>();
        }
    
        public int IdStatus { get; set; }
        public string NameStatus { get; set; }
    
        public virtual ICollection<DbOrdersOrSales> OrderOrSales { get; set; }
    }
}
